### ISSUE TITLE
Webhooks Unresponsive/Timing out

### ISSUE THREAD

**Issue by badams055** [crossplane/crossplane#4074]
### What happened?

After updating to 1.12.1 any attempt to patch a composition fails, it returns the following error stating that the webhook failed to respond. I've confirmed that the webhook starts in the crossplane pod and that the service and secrets for the webhooks exist in k8s

```
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.builder	skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called	{"GVK": "apiextensions.crossplane.io/v1, Kind=CompositeResourceDefinition"}
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.builder	Registering a validating webhook	{"GVK": "apiextensions.crossplane.io/v1, Kind=CompositeResourceDefinition", "path": "/validate-apiextensions-crossplane-io-v1-compositeresourcedefinition"}
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.webhook	Registering webhook	{"path": "/validate-apiextensions-crossplane-io-v1-compositeresourcedefinition"}
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.webhook	Registering webhook	{"path": "/validate-apiextensions-crossplane-io-v1-composition"}
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.webhook.webhooks	Starting webhook server
2023-05-15T22:35:55Z	INFO	crossplane	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
I0515 22:35:55.914985       1 leaderelection.go:248] attempting to acquire leader lease crossplane-system/crossplane-leader-election-core...
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.certwatcher	Updated current TLS certificate
2023-05-15T22:35:55Z	INFO	crossplane.controller-runtime.webhook	Serving webhook server	{"host": "", "port": 9443}
```

```
for: "composition-basic-cluster-id-noelb.yaml": error when patching "composition-basic-cluster-id-noelb.yaml": Internal error occurred: failed calling webhook "compositions.apiextensions.crossplane.io": failed to call webhook: Post "https://crossplane-webhooks.crossplane-system.svc:9443/validate-apiextensions-crossplane-io-v1-composition?timeout=10s": context deadline exceeded
```

### How can we reproduce it?

Just try to apply a patch to a composition

``` 
ka composition-basic-cluster-id-noelb.yaml
Error from server (InternalError): error when applying patch:
Resource: "apiextensions.crossplane.io/v1, Resource=compositions", GroupVersionKind: "apiextensions.crossplane.io/v1, Kind=Composition"
Name: "cluster", Namespace: ""
for: "composition-basic-cluster-id-noelb.yaml": error when patching "composition-basic-cluster-id-noelb.yaml": Internal error occurred: failed calling webhook "compositions.apiextensions.crossplane.io": failed to call webhook: Post "https://crossplane-webhooks.crossplane-system.svc:9443/validate-apiextensions-crossplane-io-v1-composition?timeout=10s": context deadline exceeded
```

### What environment did it happen in?

Crossplane version:  1.12.1
EKS
K8s 1.23
